// Tarot cards meanings retrieved from https://www.thetarotguide.com/major-arcana/
// Function that will randomly select one of the 15 tarot cards and return an object with the name and general meanings.
function getRandomCard() {
    let randNum = Math.floor(Math.random() * 15);
    console.log(randNum);
    let cardDrawn;
    if (randNum == 0) {
        cardDrawn = {
            name: `The Fool`,
            meaning: `The first card of the Major Arcana, The Fool is generally a positive card indicating new beginnings. If it appears in your readings it could mean that you are on the verge of an exciting, unexpected new adventure. Your new adventure will bring you along a path which may require you to make a leap of faith but you will grow as a result of this new experience. This new adventure could be a literal new adventure, like travelling to a place you’ve never been before. The change this card can bring will usually be a welcome one. While the Fool is generally a positive card, its appearance in a reading can also indicate that you need to take the time to look before you leap.`,
            loveAndRelationships: `The Fool in love is exciting and spontaneous but a little bit fickle. For those in relationships, The Fool indicates being so in love you can hardly contain your excitement. However, if the person asking the question is asking about commitment, this card is linked to lack of commitment or not being ready for a commitment. However, as it’s a travel card, it can also simply mean you will be going on a romantic trip such as a couple’s weekend or a honeymoon. For those that are single, it is a very good indicator that an impulsive, carefree romance is on the cards (or many such romances). If the Fool appears, prepare for a fun-filled romance but be careful not to miss true love if it comes your way during this time.`,
            moneyAndCareer: `Opportunity knocks! With the Fool in your career, it may be time to go for that new job or start your own business that you’ve been dreaming of. Other people may try to put you off or may not understand what you’re doing, be patient with them and try to make them understand but do not let them deter you. For current projects it indicates fresh new ideas and being reinvigorated with energy. The Fool indicates big opportunities for advancement. Be clever and research your opportunities and the risk but don’t be afraid to take the plunge! Financially, if you take the chance and work hard you will make more than you thought you would.`,
            health: `The Fool bodes well for physical health if you have been ill as it indicates vitality and energy. However, it can also indicate being accident prone so if you get the Fool for health be extra careful. It can also represent pregnancy as it represents the beginning of a new life.`,
            spirituality: `The Fool indicates that you are at the beginning of a new spiritual journey which will lead on to great things. You will be eager to try many different approaches, allow yourself to do this. Others may not understand the journey you’re on but you must do what is right for you.`};
    } else if (randNum == 1) {
        cardDrawn = {
            name: `The Magician`,
            meaning: `When The Magician appears in a Tarot card reading it is a sign that you have all the skills and abilities you need to be successful. The universe is aligning to bring positive changes your way. This Major Arcana trump card shows you that you must use your intellect, concentration and willpower to make things happen.  The Magician usually signifies a time in your life when you have the power to manifest the outcome you want. If it is referring to other people in your life it usually refers to someone you can learn from whose ability and wisdom will impress you.`,
            loveAndRelationships: `The Magician in the context of a love Tarot reading is a positive card. For those in relationships, The Magician Tarot signifies the relationship moving to new and deeper level where you can expect stronger commitment and happiness. If you are single The Magician indicates that now is great time to meet someone new. Your partner will be serious about you, has good intentions and will treat you well.`,
            moneyAndCareer: `In terms of money and career, The Magician Tarot points to a new opportunities presenting themselves. They will require you to make a brave move and to put your original ideas into practice. Play your cards close to your chest with certain people as The Magicians never give away their secrets. It’s a good time for promotions or starting a new business venture, you will be feeling powerful and self-assured. Big things are coming your way! You might be presented with an opportunity to mentor someone or be mentored by someone who will give you the benefit of their experience. Your finances will be improving or you will have a great opportunity to make extra money when this card appears.`,
            health: `Your strength and good health may be making a comeback if you have been ill recently or feeling drained. If your illness or ill health is not improving you may benefit from trying alternative therapies. In a health context, The Magician Tarot can indicate that an experienced, powerful healer may be needed to give you the healing boost you need.`,
            spirituality: `The Magician Tarot card in the context of spirituality indicates that now is a good time to begin some form of spiritual development. If you’ve had an interest in a spiritual subject but never made the time to pursue it, you would do well to concentrate on this pursuit in the near future as your ability to channel magical energy will be increasing dramatically. You will be surprised at how much you will benefit from this spiritual development if you concentrate your energy. For those interested in psychic development, The Magician is an excellent card to get as it points to strong latent psychic abilities coming to the fore.`
        }
    } else if (randNum == 2) {
        cardDrawn = {
            name: `The High Priestess`,
            meaning: `The High Priestess possesses intuition, mystery and sensuality combined with common sense. When the High Priestess appears in a tarot reading she indicates that now is the time to trust your instincts and go with your gut feeling. Pay attention to your dreams and the signs and symbols the universe is sending you when this Major Arcana trump card appears in your tarot reading.`,
            loveAndRelationships: `If you are a man The High Priestess appearing in your reading in a love Tarot context usually signifies you will become infatuated with an attractive feminine sensual person who may be unattainable to you. If you are a female, The High Priestess indicates that you will be highly-desired by more than one person. People will find you irresistible! If you are involved with someone The High Priestess is an indicator of good lovemaking!`,
            moneyAndCareer: `In a work context, The High Priestess can indicate that you may soon become aware of information or an opportunity that will be of benefit to you. The High Priestess Tarot card is an indicator of creativity and inspiration for those involved in the arts. For students, if The High Priestess Tarot card appears a good teacher may be coming into your life to help you in your studies. Be careful who you discuss your finances with. Keep them on a need to know basis.`,
            health: `In a health context, The High Priestess is generally telling you to listen to the messages your body is trying to send you about what it needs. The High Priestess can indicate that you are not being taken seriously in relation to your health concerns. Don’t allow your concerns to be ignored! The High Priestess can also symbolise fertility and hormones coming into balance and menstruation.`,
            spirituality: `The High Priestess Tarot card is a card of spirituality and wisdom. When this card appears it is a good time to connect with your inner voice and intuition and to trust your higher power. It is another great card to appear for those interested in psychic development!`
        }
    } else if (randNum = 3) {
        cardDrawn = {
            name: `The Empress`,
            meaning: `The Empress Tarot is the Major Arcana card of femininity and motherhood. It is also one of the strongest pregnancy cards in the Tarot deck. If you are a mother, you will really come into your own and find fulfilment. If you are a father, The Empress encourages you to build on your communication with your children and show them your nurturing side. Even if you are not a parent, when The Empress appears the message is the same, you should embrace your softer side, allow yourself to explore the emotions you are feeling and listen to your intuition. People will be drawn to you, especially those in need of the empathy, compassion and nurturing you are able to provide.`,
            loveAndRelationships: `The Empress Tarot in a love Tarot reading is a very positive card to get.  If you are single, get ready to mingle because The Empress indicates that real love and romance is on the way. If you are in a relationship it is an indicator of a committed relationship becoming deeper and more loving and affectionate. The Empress is also an indicator of good lovemaking. For those enjoying the romance The Empress card can bring you must also remember that the Empress is a strong pregnancy indicator so if you are not ready for parenthood, take proper precautions!`,
            moneyAndCareer: `In a career context, when The Empress appears in a Tarot reading, you will be feeling very creative and will inspire the people around you with your passion. You will be full of new ideas. For those trying to decide on a career or thinking of changing career, it is usually an indicator that you would do well in a creative field such as the Arts. Financially speaking this is a good time for cash flow. It’s also a good time to follow your intuition in terms of investments. As you reap the benefits, remember to share your abundance of wealth with those in need.`,
            health: `The Empress is a strong pregnancy indicator and very good omen of success for those actively trying to get pregnant. On the flip side, if you are not intending to get pregnant and you are capable of getting pregnant, The Empress is a warning to be very careful and take proper precautions! If pregnancy is not a factor in your health concerns, The Empress is an indicator that you need to nurture yourself more and listen to your body’s signals. Watch your energy levels, take time out for yourself to relax and unwind.`,
            spirituality: `When The Empress appears in a tarot reading in a spiritual context, it indicates that your intuition is telling you something and you need to slow down and take the time to listen to it. You instincts will be on point and it’s a good time to start or continue down a spiritual path as you will find it easy to connect to your higher power and everything will flow nicely for you. It indicates now is a good time to nurture your spiritual and creative gifts and connect with Mother Earth.`
        } 
    } else if (randNum == 4) {
        cardDrawn = {
            name: `The Emperor`,
            meaning: `As a person, The Emperor represents an older man who is good in business and usually wealthy. The Emperor is a solid, stable man. He is a powerful, grounded protector but he also can be rigid and stubborn. This can be a father or father-figure type or an older man you are romantically involved with. The Emperor is a hard task master and has little time for fun and frivolity. Children of The Emperor can struggle with father issues as falling short of his high expectations can affect their self-esteem. If The Emperor Tarot card appears in a past position, this Major Arcana card can indicate that the father figure in your life was authoritarian and that, while he had your best interests at heart, he may have struggled to show affection. If it appears in the present or future it’s a much better omen as it indicates a wise older man who will give you solid advice which, if you follow it, will lead you in the right direction. Generally, if not representing a person in your life, The Emperor signifies the dominance of logic over emotion and of the mind over the heart. It signifies that concentration, structure, stability and focus is required if you want to make your ideas and dreams a reality. The Emperor upright can represent fatherhood.`,
            loveAndRelationships: `If you are single and interested in men, The Emperor in a love Tarot context can indicate a romantic relationship with an older man. He will like structure, order, logic and routine. He will be a good influence on you but romance is not his strong point. He is however practical, dependable and protective. If you are single and interested in women, The Emperor Tarot is a sign that you need to be more open with your feelings. If you have feelings for someone in particular you need to bite the bullet and tell her. Don’t expect her to guess! For those already in relationships, The Emperor is a good omen of monogamy and a long lasting relationship. If you have been experiencing relationship problems they begin to improve and stability will return to the relationship.`,
            moneyAndCareer: `The Emperor in a career context indicates that your hard work will be noticed and you will reap the rewards of status and success. Concentration, focus and perseverance will get you where you want to go. If you are looking for work you will need to be persistent and logical in your job search. Good opportunities are coming that will bring structure and stability to your career. Again, it can be a sign that an older male colleague or boss will provide guidance and support to you. Financially, The Emperor is a sign that you need to be responsible and practical with your finances. You need to keep reasonable control of your spending and be aware of where your money is going. At the same time, you don’t need be a tyrant when it comes to controlling spending.`,
            health: `The Emperor in a health context can mean that you may be being too hard on yourself. Reduce or eliminate activities that are too harsh on your body, avoid punishing exercise regimes and be kind to yourself. Work with your energy levels not against them. If you are having health issues, be logical in your approach to treating them. The “suck it up and get on with it” approach will not serve you well this time. If you need to rest, rest! If you’re ill, seek medical treatment and listen to your doctor’s advice.`,
            spirituality: `The Emperor Tarot in a spirituality context can indicate that you are neglecting the spiritual part of yourself for the more physical/material side. Make time for spiritual pursuits and try not to let the logical rational part of your mind take over and stop you from exploring your sensitive side. If you are currently engaged in spiritual pursuits, The Emperor can be a sign that you need to ground and protect yourself.`
        } 
    }  else if (randNum == 5) {
        cardDrawn = {
            name: `The Lovers`,
            meaning: `The Lovers signifies perfect union, harmony, love and attraction. The Lovers can represent finding the balance within oneself. You are learning to understand yourself, your own personal moral code and what you value in life. This will bring harmony and balance to your life. In general when The Lovers Tarot card appears it is an indication that you have major choices to make or are faced with a dilemma. You may be feeling uncertain about situations, people in your life or what direction you should take. These are important decisions you are faced with. Don’t automatically go for the easy road, make sure you have all the information and make the right decision. Even if it seems like a difficult path, it will lead you on to greater things.`,
            loveAndRelationships: `In a love or relationship Tarot reading The Lovers is one of the best cards you can get! It is a soulmate card and signifies kindred spirits and an intense bond between two people. If you are single, love is coming your way! This will be more than mere infatuation. There will be an intense attraction and sexual passion as well as romance and a deep connection and mutual understanding. If you are in a relationship, this Major Arcana card tells you to expect a rekindling of the romance in your relationship. The bond between you and your partner will increase and deepen more than you can imagine. The Lovers represent you and your partner having a spiritual, emotional, mental and physical connection that most couples can only dream about. Lucky you!`,
            moneyAndCareer: `When The Lovers card appears in a career context, it can represent a business partnership between two people. If this card is representing a partnership, it will be a great partnership and mutually beneficial. You and your business partner are on the same wavelength, will work well together and be mutually supportive of each other. The Lovers in a career Tarot reading can also indicate the possibility of getting romantically involved with a work colleague. Be cautious about mixing business with pleasure, make sure you know the risks involved and are prepared for the consequences. The Lover can also signify that you have a decision to make in relation to your career path. Again it may seem like you are only faced with undesirable choices but that’s not actually the case. Gather all your facts together to make the right decision. It may indicate a big change coming or a change of job, it may seem like something you don’t want at the time but it will be good for you.  Financially, now is a good time to seek financial opportunities as you will be attracting good fortune.`,
            health: `The Lovers in a health reading is a signifier that having the right support will help you to get through any health issues. This may be a partner or friend who is offering moral support or a doctor or healthcare provider. The Lovers in a health context can simply be an indication that you have decisions to make regarding a course of treatment. The Lovers can also be related to heart health so make sure you are taking good care of your heart when this card appears.`,
            spirituality: `When The Lovers Tarot card in a spiritual context, you will be beginning to find harmony within yourself. As with the general meaning, this comes from gaining a deeper understanding of yourself, who you are and your personal morale code. This understanding leads to a deeper connection to your spiritual self. The Lovers in spiritual context can indicate that you may find it beneficial to pair up with a partner on your spiritual journey. Something simple such as taking a meditation class with a like-minded friend could be very beneficial.`
        } 
    }  else if (randNum == 6) {
        cardDrawn = {
            name: `The Hermit`,
            meaning: `The Hermit Tarot card generally indicates that you are entering a period of soul searching, self-reflection and spiritual enlightenment. You may find that you need time alone to gain a deeper understanding of yourself, to remove yourself from the daily grind in order to discover your true spiritual self, contemplate your existence, your direction in life or your values. The Hermit can also indicate isolating yourself or withdrawing into oneself in order to recover from a difficult situation. This Major Arcana trump card can suggest that you may be going through an anti-social phase where you just don’t want to interact with people as much as you normally would. The Hermit is wise, mature and knowledgeable and may be an indication of someone seeking the services of a counsellor or psychiatrist. This is a time to focus on yourself and meeting your own needs.`,
            loveAndRelationships: `In a love context, if you are single The Hermit Tarot card represents coming out the other side of a period of loneliness and solitude that may have been needed to recuperate from past heartbreak or a bad breakup. You will soon be ready for a fresh start. It can also indicate celibacy or chastity. If you are in a relationship, The Hermit upright can represent an older wiser partner. It can also suggest that you may need to make more of an effort to connect with your partner. It can indicate that you and your partner are too focused on doing your own thing rather than spending quality time together.`,
            moneyAndCareer: `The Hermit in a career context can indicate may suggest that you are putting too much focus on your career or money and materialistic pursuits, rather than sharing your attention between activities that will leave you feeling fulfilled on all levels. It can also indicate that you are wondering if you are in the right career. Money and materialism may no longer be enough to motivate you and you may find yourself seeking a new more satisfying career path. Financially, now is a time to be mature in your approach to money and investments.`,
            health: `The Hermit in a health context indicates overdoing things may lead to health issues. If you find that you’re rushed off your feet, never having a minute to take a breath, The Hermit suggests that if you don’t make time for yourself to rest and reboot your health may suffer. Take a break. Even taking a few minutes every day to meditate or just clear your mind and connect with how your body is feeling would benefit your health at this time.`,
            spirituality: `The overall theme of The Hermit is spiritual enlightenment so now is the perfect time to engage in spiritual activities. Whether it’s meditation, energy work, psychic development or connecting to your own spirit guides you are coming into a time of incredible spiritual growth. You may find yourself seeking solitude or isolating yourself in some respect. However, you should use this time to focus on evolving your spiritual side and allow yourself to take this time out to listen to your inner guidance as it will be very rewarding for you on a spiritual level.`
        } 
    }  else if (randNum == 7) {
        cardDrawn = {
            name: `Justice`,
            meaning: `The Justice Tarot card relates to karmic justice, legal matters and cause and effect. In a general context Justice is showing you that all actions have consequences. So look at your present circumstances in that context, how have your own actions contributed to where you find yourself today? Are there any karmic lessons that you should be learning from your current situation? This Major Arcana card is also a signifier of legal matters being resolved in a fair and balanced matter. This is usually a favourable omen if you are involved in a legal dispute. Justice is concerned with truth and integrity, so you may find yourself compelled to speak the truth and that you more than ever value honesty and integrity in others. Justice also relates to balance. It may signify that circumstances may arise that could throw you off balance. These circumstances may or may not be beyond your control or of your own making. Either way, you must try to keep yourself on an even-keel as events unfold. The Justice card can also indicate that you have a choice to make when it appears in your Tarot readings as you will be weighing up all your options and balancing the scales.`,
            loveAndRelationships: `In a love Tarot reading, if you are single, Justice can indicate a relationship with a person in the legal industry (judge, lawyer, legal secretary etc.) It is the Tarot card that corresponds to Libra, so a Libra may be coming into your life. If you have treated others with integrity and kindness and not been treated well in return in relationships, Justice in a love tarot reading can indicate that this imbalance is about to be corrected with the loving partner you deserve coming into your life. It can also signify that those who have treated you badly will get their comeuppance. If you are in a relationship, whether Justice is a good or bad omen really depends on the behaviour of you and your partner. If you are both being honest and acting with integrity in your relationship then you will see the rewards in the form of a period of harmony or a bigger commitment. It can indicate marriage, representing the marriage contract. However, if either of you have been dishonest or have cheated, Justice indicates that the truth will be revealed and whoever has been dishonest will reap what they have sown.`,
            moneyAndCareer: `When Justice appears in a career context, it tells you that you need to pay attention to balancing your work and personal life. Don’t forget to take adequate time out for yourself. Career is important. We all need to be able to financially support ourselves and there’s nothing wrong with having ambition. At same time, consider how many people on their deathbeds think “I wish I’d spent more time at the office.”? Remember to make time for the people who are important to you and for yourself while you’re building and maintaining a career you can be proud of. Financially, Justice can literally show you balancing your books and is a reminder that if you behave with integrity in terms of money and business you will be rewarded. If you’re going to take a bit of a gamble on something, this card is a good omen.`,
            health: `If you’ve been having health issues, Justice can indicate that you are out of balance which is contributing to your health issues. It also cautions against overindulgence in any area of your life. Try to keep everything in moderation.`,
            spirituality: `In a spiritual context, one of the main themes of Justice is karma. This does not mean that you are being punished for past mistakes. It means that you have chosen to learn certain lessons in this lifetime and the universe is sending you those lessons. The sooner you learn these lessons the better off you’ll be.`
        } 
    }  else if (randNum == 8) {
        cardDrawn = {
            name: `Death`,
            meaning: `Although it is the Tarot card that many people fear, Death generally does not mean physical death. As a rule you should never predict deaths (or the outcomes of illnesses or pregnancies for that matter) as a Tarot reader. It is unethical and irresponsible. Aside from the ethics, The Death Tarot Card usually signifies spiritual transformation and a time of change and new beginnings, not actual death! The transformation or change that Death can bring can be difficult, unexpected, sudden or even traumatic but it will bring with it a new lease of life. Its best to try not to resist the change the Death Tarot card brings as resisting it will only make the transition difficult and painful. Instead try to embrace the change as a fresh start. This Major Arcana card can also signify the need to let go of old issues or beliefs when it appears in a Tarot spread. It may be telling you that you need to draw a line under the past in order to move forward in a positive direction. A Death card transformation can be a bit of a shock to the system but ultimately it’s a positive one.`,
            loveAndRelationships: `If you are in a relationship, Death in a love tarot context can signify that you or your partner may be holding onto a relationship that’s not working or you may be clinging to old patterns that are stopping your relationship from moving forward. Death signifies that things are going to change whether you want them to or not. You can either resist the change or embrace it. If your relationship is not going well, the Death Tarot card can indicate that it may be time to walk away, it can indicate divorce or it can indicate that you and your partner need to make big changes and let go of old patterns or issues to make it work. The old issues the Death card seeks to change can be deep seated and painful. If that’s the case, you may want to consider relationship counselling. The outcome really depends on whether or not you and your partner are both willing to embrace the transformation and really want the relationship to survive because you love each other rather than because you fear not being in the relationship. The changes the Death Tarot card can bring to a relationship can be positive too, it can indicate an unexpected change like a surprise engagement or a pregnancy, you may find these changes overwhelming initially. If you are single, the Death card can indicate that you will soon be casting off the old beliefs, issues or behaviours that are no longer useful to you. Embrace this transformation as it will bring new love into your life.`,
            moneyAndCareer: `Death in a career context is a warning not to get too dependent on anything that is not working for you. The only thing in life that is guaranteed is that things change. If you are unhappy in your current job, start looking for a new one or the universe may force you to find a new job. If you are starting your own business but have been reluctant to quit your old job because of the security it offers, Death may be indicating that’s it’s time to consider jumping in with both feet. Money can be tightening when the Death card appears in a financial context, you may have a sudden drop in income or loss of money. If that happens don’t let it get you down, this change will lead you somewhere positive and you will learn from it. If you experience financial hardship, don’t stick your head in the sand, make practical adjustments and keep moving forward in a positive way. If you are tight on money, consider getting back to basics, swap big nights out for cosy nights in with close friends. And remember, any financial issues will be fine in the long run if you make the changes necessary.`,
            health: `Don’t panic if you see the Death card in health reading, again the Death card only indicates physical death in extremely rare cases and only in certain combinations! If you have been feeling like your health is never going to improve, Death can signify that a change is coming. However, how you handle this change will go a long way to determining the outcome. If your health has been bad and illness has left you feeling pessimistic, try to embrace the coming changes by changing your attitude. Try to find something positive in each day even if you feel ill. You may also try a new approach that you haven’t tried before like a different diet, holistic therapy or energy healing. Know that your current state is temporary, it will change.`,
            spirituality: `Physical death is a form of transformation when our spirits leave the physical body behind and transform back to the spiritual beings we all are intrinsically. The Death card represents spiritual transformation. In a spiritual Tarot reading, it indicates a time where you can deeply connect to your higher self and discover a depth of spirituality that you may not have even known you possessed. This spiritual transformation may be brought about by grief or loss or heartbreak that you have experienced. It can represent a difficult transition from an old situation to a new beginning. Try to embrace the change even if it is difficult, it’s leading you to your higher path.`
        } 
    }  else if (randNum == 9) {
        cardDrawn = {
            name: `The Devil`,
            meaning: `In a general context, The Devil Tarot card can signify depression or addiction. It can also be a sign of feeling trapped or restricted. With this Major Arcana card in your Tarot spread you may feel as though outside influences or forces beyond your control are restricting you, leaving you feeling powerless and victimised. However, this is the illusion The Devil creates. You are in control of your own destiny and are not bound by anything other than your own attitudes and behaviour. Don’t give up and don’t give away your power. You don’t have to tolerate negativity, criticism, manipulation or abuse from anyone. There are always options and there is always something positive you can do to improve your situation no matter how hopeless things may seem on the surface. Likewise be mindful of how you are treating others and make sure you are not trying to manipulate or control people in your life either. The Devil upright in your Tarot reading can also indicate obsessive, secretive or impulsive behaviour. It can be a sign that you are out of control. The Devil Tarot card is also a signifier of materialism and may show that you have become overly concerned with material things, status or power. These are not things that will make you truly fulfilled as a person so put your energy into the things that will.`,
            loveAndRelationships: `If you are in a relationship, The Devil can be a sign that you or your partner are feeling trapped. It may indicate a loss of freedom brought on by becoming too engrossed in a relationship. The Devil shows that this level of co-dependence is unhealthy. You and your partner should take a step back and try to rediscover some interests outside the relationship. It can also signify that you or your partner may be suffering from mental health issues that are affecting the relationship. If this is the case, seek the help of a professional counsellor to assist you both during this time. The Devil Tarot card can be a sign of jealousy, envy, deception, dominance, cheating and in an extremely negative context abuse, violence or sexual assault. Look to supporting cards to confirm this. If you feel trapped in a relationship because of any form of abuse, remember you can free yourself of this situation, don’t let The Devil make you feel powerless. If you are single, The Devil can indicate sex without love. You may be having unfulfilling or even dangerous sexual encounters or allowing yourself to be used by people who do not care about you because you desperately want to be loved. If that is the case, take a break from dating until you’ve built up your self-esteem. The Devil can also be an indicator of a potential relationship that may be harmful to you. This new love interest may have a drug addiction, become overly dependent on you possibly as a result of mental health issues, be deceptive or become violent or abusive. Although they may seem intriguing or exciting at first, The Devil indicates danger, so avoid letting this person into your life.`,
            moneyAndCareer: `In a career context, The Devil upright in your Tarot reading can indicate that you feel trapped in a job that you hate. Again, you are in control of your own life even if you don’t feel that way. Evaluate what you really want in your career and if a move is what you need, make it. Remember that it is a choice you are making if you decide to stay in a job you dislike. The Devil can also indicate a colleague or person in a career context who is deceptive and may be trying to sabotage you. Be careful who you trust, this person will be all smiles to your face and while simultaneously stabbing you in the back. In a financial context, The Devil indicates that money will be tight but it suggests that there is more you could be doing to help yourself. Watch your spending! It can easily get out of control with The Devil in your Tarot spread. Also, avoid gambling or any sort of risky or impulsive investments.`,
            spirituality: `In a spiritual context, The Devil can indicate that you have become too materialistic. Try to bring the focus back to the non-materialistic pleasures in life such as spending time with the people who make you happy or connecting to your spiritual side. It can also indicate that a lack of hope may be holding you back from moving towards the light. Like attracts like, so even in your darkest moments you should always strive to send light and love out into the world as that’s what you will attract back. Never allow darkness to take over. If you have felt overwhelmed with depression or anxiety, firstly make sure you surround yourself with a loving and supportive network of friends and let go of anybody who is overly negative or critical of you. Secondly, try some sort of energy healing to help you get rid of any negative energy you have been holding onto.`
        } 
    }  else if (randNum == 10) {
        cardDrawn = {
            name: `The Tower`,
            meaning: `Whereas the Death card is usually the card people are terrified of, out of all of the cards in the deck, The Tower is the one you really need to brace yourself for. The Tower Tarot card represents chaos and destruction. It is the Major Arcana card of sudden upheaval and unexpected change. This change usually is scary, life changing and often unavoidable. A negative Tower event can be akin to a bomb going off in your life. You don’t know how you will survive but somehow you will and later you will realise that while it was a tremendously difficult thing to go through and you wouldn’t wish it on your worst enemy, it has made you into the person you are. One positive aspect of The Tower is that the destruction it brings is usually directed at something that was built on a false beliefs and foundations or unrealistic goals and dreams. Also on the bright side, the destruction The Tower brings is always followed by renewal and creation. However, The Tower with a negative aspect can represent a whole host of tragic, traumatic or life-altering events like the death of a loved one, divorce, a bad breakup, assault, sexual assault, violence, abuse, stillbirth or miscarriage, bankruptcy, a drug overdose, a car crash or job loss to name but a few. It’s usually the kind of thing you hope will never happen to you. That said, not every Tower event denotes tragedy. If the surrounding cards are positive, The Tower can simply represent a big change, like going to live in another country. This will be a massive upheaval. It will be a scary adjustment and will change your life as you know it but ultimately the change will be a good one. Placement of The Tower is important too, in a past position in a Tarot spread it is telling you what you’ve been through. While there are some life-events that we cannot avoid, sometimes The Tower will appear in a future if you are on a path that is leading to danger to warn you to avoid it. For instance, if you tend to put yourself in dangerous situations without thinking of the consequences, The Tower may be a warning to be mindful of your safety. Or if you take big gambles with money, The Tower may be warning you that it’s time to start acting more responsibly to avert disaster. It can also warn of natural disasters such as earthquakes, tsunamis, hurricanes, tornadoes etc.`,
            loveAndRelationships: `In a love Tarot reading, if you are in a relationship, The Tower can be a bad omen representing, break-ups, separation or divorce. It can also represent either you or your partner or both, going through a difficult or traumatic event that will push your relationship to its absolute limits. If you want your relationship to survive this Tower event, you will need to try to be there for each other and maintain open and honest communication. If your relationship survives this upheaval, The Tower tells you that the relationship will have changed significantly. This may not necessarily be a bad thing as The Tower represents destruction of false beliefs too, so the relationship may come out completely changed but with a more solid and honest foundation. However, getting to that point will be one of the most difficult things you will go through as a couple. If you are single, you may find that you suddenly have to face an uncomfortable revelation about why you are single. If ego or arrogance has been getting in the way of you forming healthy relationships, it may indicate that a chaotic or destructive event is going to break down that ego. While this will not be a pleasant experience, it will teach you humility and improve your chances of a happy, healthy relationship in the future. The Tower can also indicate violence or assault so it can be a warning to be mindful of your personal safety when getting out there and meeting new people. Don’t be overly cautious but have your wits about you and take appropriate safety precautions.`,
            moneyAndCareer: `In a career context, The Tower may indicate a lack of job security. It can be a signifier of a redundancy or job loss. However, it may also indicate a big change in your current position which will bring you unwelcome stress and may prove difficult but could ultimately lead to a better position or more security. For instance, the company you work for could be bought over by another company which could cause you a lot of stress or uncertainty for a while but may eventually lead to a more secure job. Financially speaking, The Tower warns to you to be careful with money. In its extreme negative, The Tower can represent bankruptcy. Avoid risky investments. There may be an unexpected upheaval coming in financial terms so if you haven’t put any money aside for a rainy day, you’d better do so quickly.`,
            health: `In a health context, The Tower can represent a sudden illness or an accident so be mindful of your safety and well-being. If coupled with pregnancy cards it can indicate a difficult pregnancy, miscarriage, abortion or stillbirth. The Tower can also indicate mental health problems, which is understandable as Tower events generally bring with them extreme emotional turmoil. While the health issues The Tower represents are by no means easy, they are usually followed by a period of renewal. If health problems you are experiencing are forcing you to make changes in your life, try to go with the flow as these changes may ultimately prove to be for your best. Try to embrace them with a positive attitude. If you engage in any kind of substance abuse, The Tower is warning you to stop immediately or you may overdose.`,
            spirituality: `Imagine having a home you thought was solidly built and would shelter you for the rest of your life. The Tower would be a big storm that reduces your house to rubble, destroying everything you thought was secure and showing you that the foundations were not as solid as you once believed they were. While you would still have to experience sadness, loss, grief, anger and confusion at this horrible turn of events, out of the rubble you have the chance to build a new better home with more solid foundations. The Tower in a spiritual context represents the destruction of old beliefs. This could be a personal crisis of faith or some sort of scandal or revelation which will force you to rethink your whole belief system. Remember that the destruction of The Tower brings with it renewal so you may find that this sudden change actually opens you up to a more spiritual path in the long run, one that is based on a solid foundation of truth.`
        } 
    }  else if (randNum == 11) {
        cardDrawn = {
            name: `The Star`,
            meaning: `In a general context, The Star indicates hope for the future, inspiration and contentment. With this Major Arcana card in your Tarot spread you will find yourself feeling very positive, motivated and free. You will be feeling very serene and in tune with the universe as The Star is a card of spiritual connection. The Star is a very positive omen. It is the period of calm and stability that follows the storm that was The Tower. The Star indicates that you have come through your tough times with a renewed sense of yourself and the world around you, you are full of calm, well-balanced energy and you are open to healing the wounds of the past. Whatever mental, emotional, physical or spiritual issues you were experiencing are now behind you and you are ready to embrace what your future holds. Trust that the universe has a plan for you and trust the feeling you have that everything is going to be OK. You will be feeling confident in yourself and people will like you for who you are with this card in your Tarot reading. The Star can also indicate creativity and artistic flair, so now would be a great time to take up an artistic hobby.`,
            loveAndRelationships: `The Star in a love Tarot reading can indicate a relationship with an Aquarius. If you are single, The Star is an indicator that you are ready to let go of any baggage you have been carrying from past relationships. Your future love life looks positive and now is a great time to meet people. It can also signify someone from your past coming back into your life to rekindle a relationship. If you are in a relationship the Star is a sign that your relationship will be progressing into something deeper. If you have had problems in the relationship previously, The Star tells you that these issues can be healed and you can have a bright future if you open yourself up to healing.`,
            moneyAndCareer: `The Star in a career context indicates that you will have great opportunities coming your way in terms of work. If you have been waiting to find out the outcome of a promotion or job interview, The Star is very positive sign that things are going to go in your favour or something even better is going to come your way. It can also be an indicator that you would do well in a more creative role. You may be feeling very creatively inspired with The Star in your Tarot reading. Financially speaking, if you have been having money issues, The Star tells you that there is a way to get your finances in check. Now is a good time to make investments, within reason, as The Star in an upright position, signifies your finances moving in a positive direction.`,
            health: `If you have been having health issues, The Star indicates that you are coming into a time of great healing. It can be a signifier for good health and for health issues being resolved in a positive way. Or it can simply signify that you will be feeling much more hopeful about your future health.`,
            spirituality: `In a spiritual context, The Star is a great omen. It indicates that you will be very in tune with the spirit world. If you are interested in psychic development, you may find that you come on in leaps and bounds with the Star in your Tarot reading. It’s also a great time to get involved in energy or healing work as you should be very open to healing at the moment.`
        } 
    }  else if (randNum == 12) {
        cardDrawn = {
            name: `The Moon`,
            meaning: `The general meaning of The Moon Tarot card in an upright position is that everything is not as it seems. It is also the Major Arcana Tarot card of intuition. The Moons tells you that something about a situation or person in your life is not what it appears to be and you need to trust what your instincts are telling you in order to see past this illusion. The Moon also indicates that you should pay attention to your dreams as your subconscious may be bringing your attention to some information you’ve missed. The Moon can also signify that you are letting your anxiety or fear overwhelm you which may be having a negative effect on your outlook and causing you to suffer from mood swings, instability or insecurity. It can also represent a woman’s menstrual cycle. The Moon can also signify dormant insecurities or repressed issues resurfacing. The Moon Tarot card can represent underhanded or dodgy deals or illegal behaviour. If it appears in this context it is a warning to clean your act up before your behaviour is exposed. If you are awaiting a decision on something, The Moon indicates that the answer will either be delayed or be so vague it will add to your confusion rather than clarify matters.`,
            loveAndRelationships: `If you are in a relationship, The Moon Tarot card in a love Tarot reading can indicate that you may be feeling uncertain or insecure in the relationship. If your relationship looks fine to the outside world, The Moon can show that things are not as perfect as they seem. There may be miscommunication in the relationship. There could be a lot of arguments or old issues or insecurities coming to the surface. It can also signify deception, but don’t jump to conclusions if you see it in your Tarot reading. Stay calm and wait until the facts of the matter become clearer. If you are single, The Moon can indicate deceit around you or that you may be being conned. If you are dating, be mindful that this person’s intentions may not be as honourable as they seem or you may not have all the facts about them yet. It indicates that there is some piece of information that is yet to reveal itself.`,
            moneyAndCareer: `With The Moon Tarot card appearing in a career context, you may be very unclear or even anxious about your career direction. There may be miscommunication between you and your colleagues or superiors in a work context which could cause problems or misunderstandings. Alternatively, someone may be holding information back from you and you may not have all the facts you need to make a decision. In terms of finance, The Moon indicates that you should be wary of undertaking investments or any big financial gambles as you may not have all the facts you need to make an informed decision. It can also indicate that someone may be purposely deceiving you to con you out of money. Don’t be overly paranoid but do trust your instincts, if it feels like it’s too good to be true it probably is!`,
            health: `In a Health context, The Moon can signify mental health issues. It can be an indicator of anxiety disorders and depression. The Moon may also be telling you to trust your instincts in relation to your health. If you feel you have an underlying health problem, go get a check-up and push for as many tests as you need to get to the bottom of what’s affecting you. For women, The Moon can indicate a health issue relating to the menstrual cycle or being affected by a hormonal imbalance in some way.`,
            spirituality: `The Moon in a spiritual context is a great card to get as it’s all about intuition. If you are interested in psychic development or healing work, you will find everything flows really naturally for you and you are open to receiving messages from spirit with this card in your Tarot reading. Pay attention to your dreams and any thoughts, visions or gut feelings you have, your spirit guides may be trying to tell you something important! Some quiet time and meditation would be helpful here.`
        } 
    }  else if (randNum == 13) {
        cardDrawn = {
            name: `The Sun`,
            meaning: `The Sun Tarot card is the Major Arcana card of positivity, optimism, freedom and fun. When The Sun appears in an upright position, things should be going well for you as this card also represents success and enthusiasm. You will find that people are drawn to the happy vibes and positive energy you are giving out and you will bring light and joy to everyone and everything you come into contact with. You will be feeling carefree, liberated and self-assured. It is also the card of truth so if you have been the victim of lies or deception, The Sun is coming to shine its light on the deceit to reveal the truth and the perpetrators of the lies. The Sun Tarot card in an upright position also signifies good luck. Any problems you have been experiencing will melt away with the warmth this card brings. It can also indicate travel to a country with a warm climate.`,
            loveAndRelationships: `In a love Tarot spread, if you are in a relationship, The Sun is an indication great joy and happiness. It can be a sign of a period of fun, passion and positivity in your relationship. At the same time, The Sun in an upright position shines light onto everything in its path and this includes relationships, so it can also indicate that any hidden issues in your relationship will be highlighted. Any issues highlighted by The Sun will be resolved for your greater good. This can either take the form of the relationship becoming more open and honest or in some cases ending to allow a better relationship to come to you. Look to supporting cards for verification. Whatever the outcome The Sun is bringing something positive and good into your love life. The Sun can also indicate a celebration such as an engagement or wedding. If you are single, The Sun indicates that a great relationship could be coming your way. It can also indicate that you will be feeling carefree and enjoying the fun aspects of being single. Whether you are involved or single, The Sun is one of the main pregnancy indicators in the Tarot deck. If you are not ready for children, take appropriate precautions.`,
            moneyAndCareer: `In a career context, The Sun Tarot card signifies a time of great success! New opportunities will be coming your way and you will be full of optimism and enthusiasm. You will be ready and able to jump in and make any project a success. Financially, you should be doing very well with The Sun appearing in your Tarot reading as it is the Tarot card of abundance. Business ventures, investments and any sort of money making initiatives should be going well for you. If you have any hidden debts, they should also come to the surface during this time so remember to put some of your wealth aside to cover them.`,
            health: `The Sun is the card of vitality so you should be feeling full of life, balance, positivity and wellness when it appears in your tarot reading. If you have been ill, The Sun is a good omen for recovery. If you are trying to get pregnant, The Sun upright is also a good omen as it is one of the main pregnancy cards.`,
            spirituality: `In a spiritual context, The Sun Tarot card can signify discovering the joy that a spiritual path has to offer. It is the card of enlightenment. After all the challenges, trials and tribulations the Major Arcana has thrown at you, you have finally reached a place of true insight, enlightenment and contentment. You understand your path and you are happy to let things unfold in their own time as you have complete trust in the universe’s love for you and where it is leading you.`
        } 
    }  else {
        cardDrawn = {
            name: `The World`,
            meaning: `In a general context, The World Tarot card signifies having the world at your feet! This can be in a literal sense as The World is one of the Travel cards of the Major Arcana. It can represent new worlds opening up for you so you can expect to be welcomed by the people in the countries you travel to. The World can also mean you will have the world at your feet in another sense, i.e. that you will be successful and the opportunities available to you at the moment are endless. You have gone through the trials and tribulations of the rest of the Major Arcana, you have endured the hardships and learned your lessons and now you will reap the rewards. You should be proud of what you have achieved, it has not been easy to get here but you’ve done it. The universe is smiling upon you and luck is on your side when this Major Arcana card appears in your reading so grab the opportunities available to you. The World can represent the completion of a challenge such as a university course or a project or can represent finally achieving a dream or aspiration such as starting your own business, getting married or having children. You have reached the point where you can be happy with what you have accomplished. Success can bring a whole new set of challenges or worries so make sure you’re not carrying the weight of the world on your shoulders. You’ve worked hard to get to this point so stop and savour the moment! Celebrate your accomplishments.`,
            loveAndRelationships: `In a love Tarot reading, if you are in a relationship, The World can signify reaching a goal you have aspired to. That may be getting married or having children or just being in a very happy, secure, loving and committed place in your relationship. There are whole worlds opening up to you and your partner, enjoy this time, you have both had to work to get your relationship to this point. If you are single, The World signifies that there are so many options open to you. It suggests that you have worked hard to overcome your personal challenges to reach stage where you are at peace with yourself and your place in the world. This can only mean good things for you romantically, as like attracts like. When you are comfortable with yourself, happy and open to the possibilities this life has to offer you will draw someone amazing into your life. It can also be an indication that you may meet someone new while travelling or someone who travels a lot perhaps as part of their job. It also suggests that you will be popular and in-demand.`,
            moneyAndCareer: `In a career context, The World can represent reaching your career goals. If you have gone into business for yourself, it represents reaching a point, after all the stress and uncertainty of the start-up phase when you weren’t sure it would work, where your business is a success and you can finally breathe a sigh of relief! Enjoy the fruits of your hard work, you deserve it and remember to share your success with the people who helped you along the way. If you work for someone else, it can represent finally getting the position you always dreamed of or completing a successful project that will get you the recognition you deserve. The World in a career Tarot reading can also represent travelling in relation to work. In a financial context, The World indicates that money should be coming your way. However, this is not encouragement to gamble or make risky investments, rather it tells you that all the hard work you’ve been doing is going to pay off. Maybe you’ll receive an unexpected but well-deserved bonus or you will land a big contract which will give you financial security or maybe you’ll just reach the point where you feel financially secure after a long period of scrimping and saving. Whatever it is, your finances will be looking good with The World in your Tarot reading.`,
            health: `If you have been battling an illness or injury, The World is an excellent card to get as it represents successfully coming through adversity. It is a great omen for recovery. Your health generally should be on the up if The World appears in a health Tarot spread.`,
            spirituality: `In a spiritual context, The World signifies that you have come through the karmic lessons you were given and have learned from them. You now understand yourself, your path and where and how you fit into this world. This is bringing you the sense of spiritual fulfilment you have longed for. You will find you are very in tune with spirit and new planes are opening up to you. You may feel compelled to go out into the world and share your knowledge and experience.`
        }
    }
    return cardDrawn;
};

function randTopicIndex() {
    let indices = [];
    indices.push(Math.floor(Math.random() * 4))
    console.log(indices[0]);
    let secondIndex = (Math.floor(Math.random() * 4));
    console.log(secondIndex);
    for (toggle = 1; toggle = 0;) {
        if (secondIndex = indices[0]) {
            secondIndex = Math.floor(Math.random * 4);
        } else {
            indices.push(secondIndex);
            toggle = 0;
        }
    };
    console.log(indices);
    return indices;
}

function tarotReading() {
    let card = getRandomCard();
    let topics = randTopicIndex();
    console.log(`You drew ${card.name}\n`);
    console.log(card.meaning + "\n");
    for (i in topics) {
        if (topics[i] = 0) {
            console.log(`This card has something to say about your future love and relationships. ${card.loveAndRelationships}\n`);
        } else if (topics[i] = 1) {
            console.log(`${card.name} tells us about your money and career prospects. ${card.moneyAndCareer}\n`);
        } else if (topics[i] = 2) {
            console.log(`My reading informs me much about your future health. ${card.health}\n`);
        } else if (topics[i] = 3) {
            console.log(`The card you pulled lets us know of your impending spirituality. ${card.spirituality}\n`);
        }
    }
}

tarotReading();